### ISSUE TITLE
ImportError: cannot import name 'TypeDef'

### ISSUE THREAD

**Issue by hearot** [pyTeens/nylo#4]
While I was trying to launch the _Beta **nylo** Command Line™_, I got this error:
```python
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import nylo
  File "nylo/src/nylo/__init__.py", line 5, in <module>
    from .builtins import builtins
  File "nylo/src/nylo/builtins.py", line 1, in <module>
    from .derived_objects.python_linked_objects import PyStruct
  File "nylo/src/nylo/derived_objects/python_linked_objects.py", line 2, in <module>
    from nylo.struct_objects.Struct import Struct
  File "nylo/src/nylo/struct_objects/Struct.py", line 3, in <module>
    from nylo.derived_objects.syntax_unrelated_objects import (Set, Output,
ImportError: cannot import name 'TypeDef'
```
Maybe, has that happened dued to `Set`? Is it a reserved word? The answer is: **No.**
I've tried using **Python** using its own __Command Line__ and this happened:

```python
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Set
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Set' is not defined
>>> Set = lambda: "Hello"
>>> Set()
'Hello'
```

How to resolve this problem? Any ideas?

**Comment by hearot** [comment]
@hearot @veggero :p

**Comment by veggero** [comment]
@hearot I'm rewriting pieces of code. Right now, nothing runs. To try something working, go about 3/4 commits back

**Comment by hearot** [comment]
@veggero Okey, understood. So I'll maintain this issue as open.

**Comment by hearot** [comment]
Fixed.
