### ISSUE TITLE
AttributeError: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by hearot** [pyTeens/nylo#5]
```
>>> foo:
... 	int n
... -> foo(1)
... 
'str' object has no attribute 'copy'
```

The full traceback is:

```
Traceback (most recent call last):
  File "main.py", line 52, in main
    print(struct.calculate(nylo.nyglobals))
  File "/home/gabriel/PycharmProjects/nylo/src/nylo/objects/struct/struct.py", line 25, in calculate
    return self.value['self'][0].evaluate(stack)
  File "/home/gabriel/PycharmProjects/nylo/src/nylo/objects/struct/call.py", line 41, in evaluate
    self.called = Struct(self.tobdcalled.value.copy())
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by veggero** [comment]
@hearot fixed
